@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

CourseBook *-right-> "1" CourseList

CourseList -right-> Course

Course *--> CourseName
Course *--> CourseId
Course *--> UniquePersonList
Course *--> "*" Tag

UniquePersonList -right-> Person

Person *--> Name
Person *--> Phone
Person *--> Gender
Person *--> StudentId
@enduml
