@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;
:Parse command;
:Execute command
(modify Model);
:Save AddressBook to file;
:Save CourseBook to file;
stop
@enduml
