@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command

package "Parser classes"{
    Class "<<interface>>\nParser" as Parser
    Class MainParser
    Class AddStudentCommandParser
    Class RemoveStudentCommandParser
    Class RegisterCommandParser
    Class EditCourseCommandParser
    Class EditStudentCommandParser
    Class DeregisterCommandParser
    Class FindStudentByNameCommandParser
    Class FindStudentByIdCommandParser
    Class CreateCourseCommandParser
    Class DeleteCourseCommandParser
    Class FindCourseByNameCommandParser
    Class ViewCourseDetailsCommandParser
    Class CliSyntax
    Class ParserUtil
    Class ArgumentMultimap
    Class ArgumentTokenizer
    Class Prefix
}

'HiddenOutside' #FFFFFF
HiddenOutside ..> MainParser

MainParser .down.> AddStudentCommandParser: <<create>>
MainParser .down.> RemoveStudentCommandParser: <<create>>
MainParser .down.> RegisterCommandParser: <<create>>
MainParser .down.> EditCourseCommandParser: <<create>>
MainParser .down.> EditStudentCommandParser: <<create>>
MainParser .down.> DeregisterCommandParser: <<create>>
MainParser .down.> FindStudentByNameCommandParser: <<create>>
MainParser .down.> FindStudentByIdCommandParser: <<create>>
MainParser .down.> CreateCourseCommandParser: <<create>>
MainParser .down.> DeleteCourseCommandParser: <<create>>
MainParser .down.> FindCourseByNameCommandParser: <<create>>
MainParser .down.> ViewCourseDetailsCommandParser: <<create>>

'CommandParsers' #DDDDDD
AddStudentCommandParser .up.|> Parser
RemoveStudentCommandParser .up.|> Parser
RegisterCommandParser .up.|> Parser
EditCourseCommandParser .up.|> Parser
EditStudentCommandParser .up.|> Parser
DeregisterCommandParser .up.|> Parser
FindStudentByNameCommandParser .up.|> Parser
FindStudentByIdCommandParser .up.|> Parser
CreateCourseCommandParser .up.|> Parser
DeleteCourseCommandParser .up.|> Parser
FindCourseByNameCommandParser .up.|> Parser
ViewCourseDetailsCommandParser .up.|> Parser

'ParserToCommands' #FFFFFF
AddStudentCommandParser ..> AddStudentCommand : <<create>>
RemoveStudentCommandParser ..> RemoveStudentCommand : <<create>>
RegisterCommandParser ..> RegisterCommand : <<create>>
EditCourseCommandParser ..> EditCourseCommand : <<create>>
EditStudentCommandParser ..> EditStudentCommand : <<create>>
DeregisterCommandParser ..> DeregisterCommand : <<create>>
FindStudentByNameCommandParser ..> FindStudentByNameCommand : <<create>>
FindStudentByIdCommandParser ..> FindStudentByIdCommand : <<create>>
CreateCourseCommandParser ..> CreateCourseCommand : <<create>>
DeleteCourseCommandParser ..> DeleteCourseCommand : <<create>>
FindCourseByNameCommandParser ..> FindCourseByNameCommand : <<create>>
ViewCourseDetailsCommandParser ..> ViewCourseDetailsCommand : <<create>>

MainParser ..> Command : <<use>>

ArgumentTokenizer .left.> ArgumentMultimap
ArgumentTokenizer .down.> Prefix
ArgumentTokenizer ..> ArgumentMultimap

ParserUtil ..> Prefix
ParserUtil ..> seedu.address.commons.core.index.Index

CliSyntax ..> Prefix

'Commands' #F7F7F7
Class AddStudentCommand
Class RemoveStudentCommand
Class RegisterCommand
Class EditCourseCommand
Class EditStudentCommand
Class DeregisterCommand
Class FindStudentByNameCommand
Class FindStudentByIdCommand
Class CreateCourseCommand
Class DeleteCourseCommand
Class FindCourseByNameCommand
Class ViewCourseDetailsCommand

Command <|-- AddStudentCommand
Command <|-- RemoveStudentCommand
Command <|-- RegisterCommand
Command <|-- EditCourseCommand
Command <|-- EditStudentCommand
Command <|-- DeregisterCommand
Command <|-- FindStudentByNameCommand
Command <|-- FindStudentByIdCommand
Command <|-- CreateCourseCommand
Command <|-- DeleteCourseCommand
Command <|-- FindCourseByNameCommand
Command <|-- ViewCourseDetailsCommand

@enduml
