@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>> {
    Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
    Class "<<interface>>\nReadOnlyCourseBook" as ReadOnlyCourseBook
    Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
    Class "<<interface>>\nModel" as Model
    Class AddressBook
    Class CourseBook
    Class ModelManager
    Class UserPrefs

    Class UniquePersonList
    Class Person
    Class Name
    Class Phone
    Class Gender
    Class StudentId
    Class Tag

    Class CourseList
    Class Course
    Class CourseName
    Class CourseId

    Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook
CourseBook .up.|> ReadOnlyCourseBook
UserPrefs .up.|> ReadOnlyUserPrefs

ModelManager .up.|> Model
ModelManager -left-> "1" AddressBook
ModelManager --> "1" CourseBook
ModelManager -right-> "1" UserPrefs
Model .up.> ReadOnlyUserPrefs
Model .up.> ReadOnlyAddressBook
Model .up.> ReadOnlyCourseBook

AddressBook --> "1" UniquePersonList
AddressBook --> "1" UserPrefs
UniquePersonList --> "~* all" Person
Person --> Name
Person --> Phone
Person --> Gender
Person --> StudentId
Person --> "*" Tag

CourseBook --> "1" CourseList
CourseList --> "       ~* all" Course
Course --> CourseName
Course --> CourseId
Course --> "1" UniquePersonList : students >
Course --> "*" Tag

' Layout helpers
Person -[hidden]up--> I
UniquePersonList -[hidden]right-> I
Course -[hidden]up--> I
CourseList -[hidden]right-> I

Name -[hidden]right-> Phone
Phone -[hidden]right-> Gender
Gender -[hidden]right-> StudentId

CourseName -[hidden]right-> CourseId

ModelManager --> "~* filtered" Person
ModelManager --> "~* filtered" Course
@enduml
